# Generated by Django 3.0.3 on 2020-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_by', models.CharField(max_length=200, verbose_name='Created By')),
                ('comment', models.TextField(help_text='Comments..', max_length=2000)),
                ('post', models.CharField(max_length=200, verbose_name='Post Ref')),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='Enter you blog text here.', max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.IntegerField(choices=[(0, 'Publish'), (1, 'Not Publish')], default=0, verbose_name='Status')),
                ('created_by', models.CharField(max_length=200, verbose_name='Created By')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
